spring:
  application:
    name: MyAI
  config:
    import: optional:classpath:.env[.properties]
server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
# OPen AI Test
#      base-url: http://langchain4j.dev/demo/openai/v1
#      api-key: demo
#      model-name: gpt-4o-mini
#      log-requests: true
#      log-responses: true
#      timeout: 60s
       base-url: https://api.deepseek.com
       api-key: ${DEEP_SEEK_TOKEN}
#       model-name: deepseek-chat
       model-name: deepseek-reasoner # R1 推理模型
       log-requests: true
       log-responses: true
       timeout: 60s
  # 接入本地 ollama deepseek
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      log-requests: true
      log-responses: true

  # 接入阿里百炼平台
  community:
    dashscope:
      chat-model:
        api-key: ${ALI_BAILIAN_TOKEN}
        model-name: qwen-max


logging:
  level:
    root: debug


